### ISSUE TITLE
p_tqdm not installing today on Python 3.6

### ISSUE THREAD

**Issue by dan-stromberg** [swansonk14/p_tqdm#11]
Hi.

I'm seeing the following.  I'm clearing my cache, removing my pip --user directory, seeing p_tqdm have trouble installing anyway, and then I show what OS I'm on.  Although it's not shown here, I also tried upgrading my version of pip.

```
$ rm -rf ~/.cache/pip
below cmd output started 2020 Tue Jan 14 12:21:00 PM PST
above cmd output done    2020 Tue Jan 14 12:21:00 PM PST
dstromberg@dstromberg-inspiron-5570:~/src/grok/RM-454-test-train-transient x86_64-pc-linux-gnu 2521

$ rm -rf ~/.local/lib/python3.6
below cmd output started 2020 Tue Jan 14 12:21:04 PM PST
above cmd output done    2020 Tue Jan 14 12:21:04 PM PST
dstromberg@dstromberg-inspiron-5570:~/src/grok/RM-454-test-train-transient x86_64-pc-linux-gnu 2521

$ python3.6 -m pip install --user p_tqdm
below cmd output started 2020 Tue Jan 14 12:21:09 PM PST
Collecting p_tqdm
  Downloading https://files.pythonhosted.org/packages/7c/49/e0d744c3aace9e8951725c7e47c4beabf9311cc47b0ead9879a6957e18a4/p_tqdm-1.3.tar.gz
    ERROR: Complete output from command python setup.py egg_info:
    ERROR: Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-xpwevc0i/p-tqdm/setup.py", line 4, in <module>
        long_description = f.read()
      File "/usr/lib/python3.6/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 1645: ordinal not in range(128)
    ----------------------------------------
ERROR: Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-xpwevc0i/p-tqdm/
WARNING: You are using pip version 19.1.1, however version 19.3.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
above cmd output done    2020 Tue Jan 14 12:21:16 PM PST
dstromberg@dstromberg-inspiron-5570:~/src/grok/RM-454-test-train-transient x86_64-pc-linux-gnu 2521

$ cat /etc/lsb-release 
below cmd output started 2020 Tue Jan 14 12:21:20 PM PST
DISTRIB_ID=LinuxMint
DISTRIB_RELEASE=19.3
DISTRIB_CODENAME=tricia
DISTRIB_DESCRIPTION="Linux Mint 19.3 Tricia"
```

Is this happening to everyone?  What can I do to get it installed?

Thanks!

**Comment by dan-stromberg** [comment]
I see this happening also on one of my home machines:
```
$ cat /etc/lsb-release 
below cmd output started 2020 Tue Jan 14 12:33:56 PM PST
DISTRIB_ID=LinuxMint
DISTRIB_RELEASE=19.2
DISTRIB_CODENAME=tina
DISTRIB_DESCRIPTION="Linux Mint 19.2 Tina"
above cmd output done    2020 Tue Jan 14 12:33:56 PM PST
dstromberg@dell-inspiron:~ x86_64-pc-linux-gnu 19861

$ python3.6 -m pip install --user p_tqdm
below cmd output started 2020 Tue Jan 14 12:34:01 PM PST
Collecting p_tqdm
  Using cached https://files.pythonhosted.org/packages/7c/49/e0d744c3aace9e8951725c7e47c4beabf9311cc47b0ead9879a6957e18a4/p_tqdm-1.3.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-57sgqgca/p-tqdm/setup.py", line 4, in <module>
        long_description = f.read()
      File "/usr/lib/python3.6/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 1645: ordinal not in range(128)
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-57sgqgca/p-tqdm/
```

**Comment by dan-stromberg** [comment]
I created a new/empty linux account on the first system (a work machine), and got the same error:
```
$ python3.6 -m pip install --user p_tqdm
Collecting p_tqdm
  Downloading https://files.pythonhosted.org/packages/7c/49/e0d744c3aace9e8951725c7e47c4beabf9311cc47b0ead9879a6957e18a4/p_tqdm-1.3.tar.gz
    ERROR: Complete output from command python setup.py egg_info:
    ERROR: Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-_7zmy7ah/p-tqdm/setup.py", line 4, in <module>
        long_description = f.read()
      File "/usr/lib/python3.6/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 1645: ordinal not in range(128)
    ----------------------------------------
ERROR: Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-_7zmy7ah/p-tqdm/
WARNING: You are using pip version 19.1.1, however version 19.3.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```

**Comment by dan-stromberg** [comment]
Same problem on a freshly-installed CentOS 7.6 system:
```
$ python3.6 -m pip install --user p_tqdm
cmd output started 2020 Tue Jan 14 04:28:14 PM EST
Collecting p_tqdm
  Downloading https://files.pythonhosted.org/packages/7c/49/e0d744c3aace9e8951725c7e47c4beabf9311cc47b0ead9879a6957e18a4/p_tqdm-1.3.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-l_18ge5n/p-tqdm/setup.py", line 4, in <module>
        long_description = f.read()
      File "/usr/lib64/python3.6/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 1645: ordinal not in range(128)
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-l_18ge5n/p-tqdm/
```

**Comment by dan-stromberg** [comment]
1.2 works.  1.3 continues to have trouble:
```
$ python3.6 -m pip install --user p_tqdm==1.2
below cmd output started 2020 Tue Jan 14 01:30:33 PM PST
Collecting p_tqdm==1.2
  Downloading https://files.pythonhosted.org/packages/52/ba/6c00fc368f75190d39a55fbdc27ff9be872b6fa97d68ddd758a60a71ffec/p_tqdm-1.2.tar.gz
Collecting pathos (from p_tqdm==1.2)
  Downloading https://files.pythonhosted.org/packages/c6/a2/cd59f73d5ede4f122687bf8f63de5d671c9561e493ca699241f05b038278/pathos-0.2.5.tar.gz (162kB)
     |################################| 163kB 7.3MB/s 
Collecting tqdm (from p_tqdm==1.2)
  Downloading https://files.pythonhosted.org/packages/72/c9/7fc20feac72e79032a7c8138fd0d395dc6d8812b5b9edf53c3afd0b31017/tqdm-4.41.1-py2.py3-none-any.whl (56kB)
     |################################| 61kB 12.4MB/s 
Collecting dill>=0.3.1 (from pathos->p_tqdm==1.2)
  Downloading https://files.pythonhosted.org/packages/c7/11/345f3173809cea7f1a193bfbf02403fff250a3360e0e118a1630985e547d/dill-0.3.1.1.tar.gz (151kB)
     |################################| 153kB 11.4MB/s 
Collecting multiprocess>=0.70.9 (from pathos->p_tqdm==1.2)
  Downloading https://files.pythonhosted.org/packages/58/17/5151b6ac2ac9b6276d46c33369ff814b0901872b2a0871771252f02e9192/multiprocess-0.70.9.tar.gz (1.6MB)
     |################################| 1.6MB 11.6MB/s 
Collecting pox>=0.2.7 (from pathos->p_tqdm==1.2)
  Downloading https://files.pythonhosted.org/packages/6c/9a/957818485aa165ce93b646aeb20181215bb415c9dca8345bdbe23b08ae67/pox-0.2.7.tar.gz (110kB)
     |################################| 112kB 12.7MB/s 
Collecting ppft>=1.6.6.1 (from pathos->p_tqdm==1.2)
  Downloading https://files.pythonhosted.org/packages/5b/16/9e83c2aa45949ee9cd6e8731275acdaeb6c624b8728d6598196c65074f3e/ppft-1.6.6.1.tar.gz (63kB)
     |################################| 71kB 8.6MB/s 
Requirement already satisfied: six>=1.7.3 in /usr/lib/python3/dist-packages (from ppft>=1.6.6.1->pathos->p_tqdm==1.2) (1.11.0)
Installing collected packages: dill, multiprocess, pox, ppft, pathos, tqdm, p-tqdm
  Running setup.py install for dill ... done
  Running setup.py install for multiprocess ... done
  Running setup.py install for pox ... done
  Running setup.py install for ppft ... done
  Running setup.py install for pathos ... done
  Running setup.py install for p-tqdm ... done
Successfully installed dill-0.3.1.1 multiprocess-0.70.9 p-tqdm-1.2 pathos-0.2.5 pox-0.2.7 ppft-1.6.6.1 tqdm-4.41.1
WARNING: You are using pip version 19.1.1, however version 19.3.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
above cmd output done    2020 Tue Jan 14 01:30:41 PM PST
dstromberg@dstromberg-inspiron-5570:~/src/grok/RM-454-test-train-transient x86_64-pc-linux-gnu 2521

$ python3.6 -m pip install --user p_tqdm==1.3
below cmd output started 2020 Tue Jan 14 01:30:44 PM PST
Collecting p_tqdm==1.3
  Using cached https://files.pythonhosted.org/packages/7c/49/e0d744c3aace9e8951725c7e47c4beabf9311cc47b0ead9879a6957e18a4/p_tqdm-1.3.tar.gz
    ERROR: Complete output from command python setup.py egg_info:
    ERROR: Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-uukm8b_u/p-tqdm/setup.py", line 4, in <module>
        long_description = f.read()
      File "/usr/lib/python3.6/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 1645: ordinal not in range(128)
    ----------------------------------------
ERROR: Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-uukm8b_u/p-tqdm/
WARNING: You are using pip version 19.1.1, however version 19.3.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```

**Comment by captbuckrogers25** [comment]
Same on FreeBSD 12.1 python3.6.9.  1.2 installs fine.

**Comment by swansonk14** [comment]
Hi @captbuckrogers25, thank you for noticing this issue and sorry for not taking a look earlier! I had tried installing `p_tqdm` on both MacOS and Ubuntu but hadn't run into any issues so I didn't realise it was a problem.

I haven't been able to reproduce the problem so I can't guarantee that I've fixed it, but I tried looking up that issue and it seems like it's an encoding issue that can be fixed by specifying the encoding when reading a file. I made the fix in this PR https://github.com/swansonk14/p_tqdm/commit/0c8f179f8cc315a01e9c8327f1e10cde6062e6a6 and created a new release with that fix https://github.com/swansonk14/p_tqdm/releases/tag/v_1.3.1.

Try installing p_tqdm version 1.3.1 and please let me know if you run into any further issues.
