### ISSUE TITLE
No six dependency?

### ISSUE THREAD

**Issue by slhck** [swansonk14/p_tqdm#12]
After installing this project, I run into the following error upon import:

```
    from p_tqdm import p_umap
  File "/home/werner/.cache/pypoetry/virtualenvs/streaming-qoe-logs-9HyVvwyT-py3.7/lib/python3.7/site-packages/p_tqdm/__init__.py", line 1, in <module>
    from p_tqdm.p_tqdm import p_map, p_imap, p_umap, p_uimap, t_map, t_imap
  File "/home/werner/.cache/pypoetry/virtualenvs/streaming-qoe-logs-9HyVvwyT-py3.7/lib/python3.7/site-packages/p_tqdm/p_tqdm.py", line 13, in <module>
    from pathos.helpers import cpu_count
  File "/home/werner/.cache/pypoetry/virtualenvs/streaming-qoe-logs-9HyVvwyT-py3.7/lib/python3.7/site-packages/pathos/__init__.py", line 55, in <module>
    from . import pools
  File "/home/werner/.cache/pypoetry/virtualenvs/streaming-qoe-logs-9HyVvwyT-py3.7/lib/python3.7/site-packages/pathos/pools.py", line 31, in <module>
    from pathos.helpers import ProcessPool as _ProcessPool
  File "/home/werner/.cache/pypoetry/virtualenvs/streaming-qoe-logs-9HyVvwyT-py3.7/lib/python3.7/site-packages/pathos/helpers/__init__.py", line 9, in <module>
    from . import pp_helper
  File "/home/werner/.cache/pypoetry/virtualenvs/streaming-qoe-logs-9HyVvwyT-py3.7/lib/python3.7/site-packages/pathos/helpers/pp_helper.py", line 30, in <module>
    from pp import _Task
  File "/home/werner/.cache/pypoetry/virtualenvs/streaming-qoe-logs-9HyVvwyT-py3.7/lib/python3.7/site-packages/pp/__init__.py", line 12, in <module>
    from ._pp import *
  File "/home/werner/.cache/pypoetry/virtualenvs/streaming-qoe-logs-9HyVvwyT-py3.7/lib/python3.7/site-packages/pp/_pp.py", line 62, in <module>
    import six
ModuleNotFoundError: No module named 'six'
```

My poetry dependencies are:

```
python = "^3.7"
tqdm = "^4.41.1"
numpy = "^1.18.1"
p_tqdm = "^1.3"
```

Is there any explicit dependency missing here?

**Comment by slhck** [comment]
I should add that everything runs once I do `poetry add six`.

**Comment by swansonk14** [comment]
Hi @slhck, I tried installing p_tqdm and the other dependencies using the exact same versions and it works for me. From the error message it looks like the import is happening within the `pathos` multiprocessing library, which seems to make use of `six`. I'm using conda to manage my dependencies and it looks like conda automatically installs `six` when installing `p_tqdm` since it's a dependency of `pathos`, even though `six` isn't explicitly used in `p_tqdm`.

Since conda manages to install `six` correctly and since `six` isn't an explicit dependence of `p_tqdm`, I'm not going to add it to the requirements. But if you keep having this problem you can always just run `poetry add six` or use a different dependency manager like conda.

**Comment by slhck** [comment]
I understand that this is probably an issue with a dependency and not your tool, but would there be any downsides to just adding the `six` dependency nonetheless?

Please consider that not all users are working with conda, so the fact that it works for you is just a consequence of using this particular distribution. With a plain vanilla Python installation, using this package is not straightforward and just fails because it requires additional, undocumented steps. 

So far I haven't yet come across a Python package that requires you to manually install a dependency and does not work otherwise … so for the end user it would be a huge benefit to just specify the `six` package as a requirement.

```
~/Desktop/test via 🐍 3.7.3 took 9s
➜ poetry add p_tqdm
Creating virtualenv test-Caqnx6v6-py3.7 in /Users/werner/Library/Caches/pypoetry/virtualenvs
Using version ^1.3.1 for p_tqdm

Updating dependencies
Resolving dependencies... (4.8s)

Writing lock file


Package operations: 7 installs, 0 updates, 0 removals

  - Installing dill (0.3.1.1)
  - Installing multiprocess (0.70.9)
  - Installing pox (0.2.7)
  - Installing ppft (1.6.6.1)
  - Installing pathos (0.2.5)
  - Installing tqdm (4.43.0)
  - Installing p-tqdm (1.3.1)

~/Desktop/test via 🐍 3.7.3 took 20s
➜ poetry run python3 -c "import p_tqdm"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/werner/Library/Caches/pypoetry/virtualenvs/test-Caqnx6v6-py3.7/lib/python3.7/site-packages/p_tqdm/__init__.py", line 1, in <module>
    from p_tqdm.p_tqdm import p_map, p_imap, p_umap, p_uimap, t_map, t_imap
  File "/Users/werner/Library/Caches/pypoetry/virtualenvs/test-Caqnx6v6-py3.7/lib/python3.7/site-packages/p_tqdm/p_tqdm.py", line 13, in <module>
    from pathos.helpers import cpu_count
  File "/Users/werner/Library/Caches/pypoetry/virtualenvs/test-Caqnx6v6-py3.7/lib/python3.7/site-packages/pathos/__init__.py", line 55, in <module>
    from . import pools
  File "/Users/werner/Library/Caches/pypoetry/virtualenvs/test-Caqnx6v6-py3.7/lib/python3.7/site-packages/pathos/pools.py", line 31, in <module>
    from pathos.helpers import ProcessPool as _ProcessPool
  File "/Users/werner/Library/Caches/pypoetry/virtualenvs/test-Caqnx6v6-py3.7/lib/python3.7/site-packages/pathos/helpers/__init__.py", line 9, in <module>
    from . import pp_helper
  File "/Users/werner/Library/Caches/pypoetry/virtualenvs/test-Caqnx6v6-py3.7/lib/python3.7/site-packages/pathos/helpers/pp_helper.py", line 30, in <module>
    from pp import _Task
  File "/Users/werner/Library/Caches/pypoetry/virtualenvs/test-Caqnx6v6-py3.7/lib/python3.7/site-packages/pp/__init__.py", line 12, in <module>
    from ._pp import *
  File "/Users/werner/Library/Caches/pypoetry/virtualenvs/test-Caqnx6v6-py3.7/lib/python3.7/site-packages/pp/_pp.py", line 62, in <module>
    import six
ModuleNotFoundError: No module named 'six'
```

**Comment by swansonk14** [comment]
Good point, I guess there's no harm in adding the dependency. I just added it in this release: https://github.com/swansonk14/p_tqdm/releases/tag/v_1.3.2. Can you try installing it now (`pip install p_tqdm==1.3.2`) and let me know if it works?

**Comment by slhck** [comment]
I can confirm that this works now. Installation succeeds without any additional steps. Thanks!
