### ISSUE TITLE
ModuleNotFoundError: No module named 'tqdm.auto

### ISSUE THREAD

**Issue by ibtorkil** [swansonk14/p_tqdm#48]
Stable diffusion runs perfectly well until you install any extension which calls for  tqdm , I've tried with multiple extensions, and its hit and miss which ones contained this error .. but it completely breaks stable diffusion which then refuses to launch once the extension has been added,  

"Launching Web UI with arguments: --xformers --medvram
Traceback (most recent call last):
  File "C:\1ststable\stable-diffusion-webui-1.6.0-RC\launch.py", line 41, in <module>
    main()
  File "C:\1ststable\stable-diffusion-webui-1.6.0-RC\launch.py", line 37, in main
    start()
  File "C:\1ststable\stable-diffusion-webui-1.6.0-RC\modules\launch_utils.py", line 439, in start
    import webui
  File "C:\1ststable\stable-diffusion-webui-1.6.0-RC\webui.py", line 13, in <module>
    initialize.imports()
  File "C:\1ststable\stable-diffusion-webui-1.6.0-RC\modules\initialize.py", line 21, in imports
    import gradio  # noqa: F401
  File "C:\1ststable\stable-diffusion-webui-1.6.0-RC\venv\lib\site-packages\gradio\__init__.py", line 3, in <module>
    import gradio.components as components
  File "C:\1ststable\stable-diffusion-webui-1.6.0-RC\venv\lib\site-packages\gradio\components\__init__.py", line 1, in <module>
    from gradio.components.annotated_image import AnnotatedImage
  File "C:\1ststable\stable-diffusion-webui-1.6.0-RC\venv\lib\site-packages\gradio\components\annotated_image.py", line 8, in <module>
    from gradio_client.documentation import document, set_documentation_group
  File "C:\1ststable\stable-diffusion-webui-1.6.0-RC\venv\lib\site-packages\gradio_client\__init__.py", line 1, in <module>
    from gradio_client.client import Client
  File "C:\1ststable\stable-diffusion-webui-1.6.0-RC\venv\lib\site-packages\gradio_client\client.py", line 24, in <module>
    from huggingface_hub import CommitOperationAdd, SpaceHardware, SpaceStage
  File "C:\1ststable\stable-diffusion-webui-1.6.0-RC\venv\lib\site-packages\huggingface_hub\__init__.py", line 322, in __getattr__
    submod = importlib.import_module(submod_path)
  File "C:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "C:\1ststable\stable-diffusion-webui-1.6.0-RC\venv\lib\site-packages\huggingface_hub\hf_api.py", line 35, in <module>
    from huggingface_hub.utils import (
  File "C:\1ststable\stable-diffusion-webui-1.6.0-RC\venv\lib\site-packages\huggingface_hub\utils\__init__.py", line 18, in <module>
    from . import tqdm as _tqdm  # _tqdm is the module
  File "C:\1ststable\stable-diffusion-webui-1.6.0-RC\venv\lib\site-packages\huggingface_hub\utils\tqdm.py", line 63, in <module>
    from tqdm.auto import tqdm as old_tqdm
ModuleNotFoundError: No module named 'tqdm.auto'
Press any key to continue . . .

**Comment by ibtorkil** [comment]
This is what I've found to get stable diffusion running again , but it may break functionality.

pip install tqdm==4.57.0

This install a version in which the bug doesn't occur .to do so

C:\>cd c:\1ststable\stable-diffusion-webui-1.6.0-RC\venv\Scripts

c:\1ststable\stable-diffusion-webui-1.6.0-RC\venv\Scripts>activate.bat
Venv will appear on the left before the drive number, (venv) c: 
which will allow you to install the specific version of tqdm in this case the functional one being 4.57.0

(venv) c:\1ststable\stable-diffusion-webui-1.6.0-RC\venv\Scripts>pip install tqdm==4.57.0
Collecting tqdm==4.57.0
  Downloading tqdm-4.57.0-py2.py3-none-any.whl (72 kB)
     ---------------------------------------- 73.0/73.0 kB 366.8 kB/s eta 0:00:00
Installing collected packages: tqdm
  Attempting uninstall: tqdm
    Found existing installation: tqdm 4.11.2
    Uninstalling tqdm-4.11.2:
      Successfully uninstalled tqdm-4.11.2
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
moviepy 0.2.3.2 requires tqdm==4.11.2, but you have tqdm 4.57.0 which is incompatible.
Successfully installed tqdm-4.57.0

and it will need to be repeated in every folder(separate installation ) you use stable diffusion in .. it doesn't appear to fix system wide for alternate setups you may have
